### ISSUE TITLE
Update the user guide

### ISSUE THREAD

**Issue by okkhoy** [CS2103JAN2018-W11-B1/main#85]
Hi guys,

Please update the user guide to reflect the complete project features. 
For the convenience of understanding your planning, please indicate which the feature/command will appear in which version. Please note, this won't affect your grading in anyway!

However, you need to indicate features that are a part of future work explicitly as `coming in v2.0` to help us understand how you have thought your project through.

Cheers,
Akshay

**Comment by Aussiroth** [comment]
All completed and planned 2.0 features have been updated and are in v1.5 user guide, so closing this issue now.
